# Pre-commit 配置
# 安装HOOK： uv run pre-commit install --hook-type pre-commit --hook-type pre-push
# 手工运行 commit检查： uv run pre-commit run --hook-stage pre-commit --all-files
# 手工运行 push检查： uv run pre-commit run --hook-stage pre-push --all-files

repos:
  - repo: local
    hooks:
      # ----------- pre-commit 阶段的钩子 -----------
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python]
      
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        args: ["--fix"]
        language: system
        types_or: [python]
        
      - id: mypy
        name: mypy
        entry: uv run mypy
        args: ["."]
        language: system
        pass_filenames: false # 不传递文件名，因为 mypy 会自动选择相关模块

      - id: pytest
        name: pytest (unit + testmon)
        entry: uv run pytest
        args: ["--testmon", "-m", "unit"]
        language: system
        pass_filenames: false # 不传递文件名，因为 testmon 会自动选择相关测试

