"""Raw 整理管线专属产品级默认值。

- **`DEFAULT_RAW_JUNK_KEYWORDS`**：2.1 目录 basename、2.2 / 3.0 stem；命中语义为 **token 边界匹配**
  （见 ``shared/utils/name_keyword_match``：NFKC + casefold + 分隔符 / Unicode ``Z*``、``P*``），非纯子串包含。
- **`DEFAULT_RAW_CLEANUP_JUNK_MAX_BYTES`**：递归清洗阶段（2.2）中仅当 stem 命中 junk 关键字时，
  单文件须 **`st_size` 严格小于** 该值（默认 100MiB）才删除；扩展名 / 0 字节规则不受此上限约束。

Raw **视频归桶**（`files_misc` 第一层视频 stem 匹配，即阶段 3.4）：关键字匹配顺序：
`movie` → `video_US_VR` → `video_US`；均未命中则通过 ``generate_jav_filename`` 识别番号，
番号前缀属于 ``DEFAULT_JAV_VR_SERIAL_PREFIXES`` 归入 `video_jav_vr`，
其余已识别番号归入 `video_jav`，无番号归入 **`files_video_misc`**。
"""

DEFAULT_RAW_JUNK_KEYWORDS: tuple[str, ...] = (
    "FC2-PPV",
    "RARBG_DO_NOT_MIRROR",
    "发布器",
    "社区回家指南",
    "论坛文宣",
    "美女直播",
    "手机网址",
    "新地址",
    "扫码",
    "二维码",
    "影视联盟",
    "安卓APP",
    "文宣",
    "手机版网址",
)

DEFAULT_RAW_CLEANUP_JUNK_MAX_BYTES: int = 100 * 1024 * 1024

DEFAULT_RAW_VIDEO_BUCKET_MOVIE_KEYWORDS: tuple[str, ...] = ("AMZN",)

DEFAULT_RAW_VIDEO_BUCKET_US_VR_KEYWORDS: tuple[str, ...] = (
    "LethalHardcoreVR",
    "AsianSexVR",
    "VirtualTaboo",
    "VRLatina",
    "FuckPassVR",
    "TabooVR",
    "BadoinkVR",
    "CzechVR",
    "CzechVRFetish",
    "VRSpy",
    "VRCosplayX",
    "VirtualRealPorn",
    "RealJamVR",
    "BadoinkVR",
    "VRedging",
    # 低优先级，排在后面
    "SLR",
    "VR",
)

DEFAULT_RAW_VIDEO_BUCKET_US_KEYWORDS: tuple[str, ...] = (
    "AcademyPOV",
    "AccidentalGangbang",
    "AllAnalAllTheTime",
    "AltErotic",
    "AnalVids",
    "Assylum",
    "BackroomCastingCouch",
    "BangSurprise",
    "BoundGangBangs",
    "BrookelynneBriar",
    "CathysCraving",
    "CherryPimps",
    "Clips4Sale",
    "ClubSeventeen",
    "ClubSweethearts",
    "DefeatedSexFight",
    "DeviceBondage",
    "DevilsFilm",
    "DigitalPlayground",
    "DivineBitches",
    "DorcelClub",
    "DungeonSex",
    "EvilAngel",
    "ExploitedCollegeGirls",
    "FemdomEmpire",
    "FilthyTaboo",
    "FittingRoom",
    "FootsieBabes",
    "FrolicMe",
    "FTVGirls",
    "GangbangCreampie",
    "GirlsOutWest",
    "GroupBanged",
    "HardcoreGangBang",
    "HardTied",
    "Hentaied",
    "HollandschePassie",
    "HouseOfTaboo",
    "HumiliationPOV",
    "iWantClips",
    "JacquieEtMichelTV",
    "JulesJordan",
    "JuliaAnnLive",
    "KarupsOW",
    "KendraJames",
    "LadySonia",
    "LegalPorno",
    "Lustery",
    "ManyVids",
    "MatureNL",
    "MaxineX",
    "MetArtX",
    "Milfy",
    "MistressT",
    "MomComesFirst",
    "PascalsSubSluts",
    "PerverseFamily",
    "PinkoTGirls",
    "PissVids",
    "PornBox",
    "PornMegaLoad",
    "PowerFetish",
    "PrimalFetish",
    "Private",
    "PureTaboo",
    "RedXXX",
    "SexAndSubmission",
    "SexMex",
    "SexuallyBroken",
    "Shoplyfter",
    "Spizoo",
    "StrapLez",
    "SubmissiveCuckolds",
    "SweetSinner",
    "TabooHeat",
    "TadpolexStudio",
    "TeamSkeetSelects",
    "Teenslikeitbig",
    "TeensLoveBlackCocks",
    "TeenyTaboo",
    "TransAngels",
    "Wanilianna",
    "WankItNow",
    "WetAndPuffy",
    "WhenGirlsPlay",
    "WildOnCam",
    "WoodmanCastingX",
    "XevBellringer",
    "Z-Filmz",
    # 低优先级1
    "Beauty4K",
    "GirlCum",
    # 低优先级2
    "Kink",
    "Brazzers",
    "Babes",
    "Blacked",
    "Throated",
    "Taboo",
)
